language: cpp

sudo: required

dist: bionic

branches:
  only:
    - master

os:
  - linux

compiler:
  - g++

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq g++-7
  - sudo apt-get install -qq cmake

addons:
  apt:
    packages: libboost-all-dev

script:
    - cd src/examples
    - mkdir build && cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug ..
    - make -j8
